[2025-06-22T01:21:10.921+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T01:21:10.959+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract manual__2025-06-22T01:21:03.150666+00:00 [queued]>
[2025-06-22T01:21:10.972+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract manual__2025-06-22T01:21:03.150666+00:00 [queued]>
[2025-06-22T01:21:10.974+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-22T01:21:11.006+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-06-22 01:21:03.150666+00:00
[2025-06-22T01:21:11.038+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=29) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-22T01:21:11.030+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'extract', 'manual__2025-06-22T01:21:03.150666+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp4cjy5zfn']
[2025-06-22T01:21:11.040+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask extract
[2025-06-22T01:21:11.040+0000] {standard_task_runner.py:63} INFO - Started process 38 to run task
[2025-06-22T01:21:11.209+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.extract manual__2025-06-22T01:21:03.150666+00:00 [running]> on host dfe01f22a6ea
[2025-06-22T01:21:11.395+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T01:21:03.150666+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T01:21:03.150666+00:00'
[2025-06-22T01:21:11.400+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T01:21:15.546+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T01:21:15.548+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/extract_postgres.py", line 5, in extract_postgres
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known

[2025-06-22T01:21:15.575+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=extract, run_id=manual__2025-06-22T01:21:03.150666+00:00, execution_date=20250622T012103, start_date=20250622T012110, end_date=20250622T012115
[2025-06-22T01:21:15.609+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task extract (could not translate host name "db" to address: Name or service not known
; 38)
[2025-06-22T01:21:15.635+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T01:21:15.663+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T01:21:15.681+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
