[2025-06-22T17:44:21.525+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T17:44:21.554+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.transform manual__2025-06-22T17:44:10.986771+00:00 [queued]>
[2025-06-22T17:44:21.565+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.transform manual__2025-06-22T17:44:10.986771+00:00 [queued]>
[2025-06-22T17:44:21.565+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-22T17:44:21.588+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2025-06-22 17:44:10.986771+00:00
[2025-06-22T17:44:21.597+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'transform', 'manual__2025-06-22T17:44:10.986771+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmplakalzpg']
[2025-06-22T17:44:21.600+0000] {standard_task_runner.py:91} INFO - Job 79: Subtask transform
[2025-06-22T17:44:21.606+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=49) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-22T17:44:21.607+0000] {standard_task_runner.py:63} INFO - Started process 58 to run task
[2025-06-22T17:44:21.674+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.transform manual__2025-06-22T17:44:10.986771+00:00 [running]> on host 1b312d24d1ba
[2025-06-22T17:44:21.832+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T17:44:10.986771+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T17:44:10.986771+00:00'
[2025-06-22T17:44:21.834+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T17:44:21.982+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T17:44:21.983+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/transform_with_spark.py", line 4, in transform_with_spark
    spark = SparkSession.builder.appName("ETL").getOrCreate()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 556, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/core/context.py", line 523, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/core/context.py", line 205, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/core/context.py", line 444, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 111, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-06-22T17:44:22.001+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=transform, run_id=manual__2025-06-22T17:44:10.986771+00:00, execution_date=20250622T174410, start_date=20250622T174421, end_date=20250622T174422
[2025-06-22T17:44:22.031+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 79 for task transform ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 58)
[2025-06-22T17:44:22.062+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T17:44:22.116+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T17:44:22.132+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
