[2025-06-22T01:40:11.020+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T01:40:11.049+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load manual__2025-06-22T01:40:01.463246+00:00 [queued]>
[2025-06-22T01:40:11.059+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load manual__2025-06-22T01:40:01.463246+00:00 [queued]>
[2025-06-22T01:40:11.059+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-22T01:40:11.085+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2025-06-22 01:40:01.463246+00:00
[2025-06-22T01:40:11.095+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'load', 'manual__2025-06-22T01:40:01.463246+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmprajt1u6f']
[2025-06-22T01:40:11.097+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask load
[2025-06-22T01:40:11.098+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=47) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-22T01:40:11.099+0000] {standard_task_runner.py:63} INFO - Started process 56 to run task
[2025-06-22T01:40:11.164+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.load manual__2025-06-22T01:40:01.463246+00:00 [running]> on host 4ebd17c42323
[2025-06-22T01:40:11.257+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T01:40:01.463246+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T01:40:01.463246+00:00'
[2025-06-22T01:40:11.258+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T01:40:11.269+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T01:40:11.270+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load_to_hive.py", line 17, in load_to_hive
    conn = hive.Connection(host='hive-server', port=10000, username='hive')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyhive/hive.py", line 242, in __init__
    import thrift_sasl
ModuleNotFoundError: No module named 'thrift_sasl'
[2025-06-22T01:40:11.284+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=load, run_id=manual__2025-06-22T01:40:01.463246+00:00, execution_date=20250622T014001, start_date=20250622T014011, end_date=20250622T014011
[2025-06-22T01:40:11.306+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task load (No module named 'thrift_sasl'; 56)
[2025-06-22T01:40:11.314+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T01:40:11.330+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T01:40:11.332+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
