[2025-06-22T02:52:53.317+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T02:52:53.345+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract manual__2025-06-22T02:52:47.920817+00:00 [queued]>
[2025-06-22T02:52:53.355+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract manual__2025-06-22T02:52:47.920817+00:00 [queued]>
[2025-06-22T02:52:53.356+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-22T02:52:53.410+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-06-22 02:52:47.920817+00:00
[2025-06-22T02:52:53.415+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'extract', 'manual__2025-06-22T02:52:47.920817+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp6_ww_muf']
[2025-06-22T02:52:53.417+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask extract
[2025-06-22T02:52:53.419+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=37) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-22T02:52:53.420+0000] {standard_task_runner.py:63} INFO - Started process 46 to run task
[2025-06-22T02:52:53.564+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.extract manual__2025-06-22T02:52:47.920817+00:00 [running]> on host 1e0f4d6a7c04
[2025-06-22T02:52:53.780+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T02:52:47.920817+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T02:52:47.920817+00:00'
[2025-06-22T02:52:53.781+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T02:52:53.816+0000] {logging_mixin.py:188} INFO - Extrayendo tabla: order_line
[2025-06-22T02:52:53.820+0000] {logging_mixin.py:188} WARNING - /opt/airflow/dags/scripts/extract_postgres.py:25 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-22T02:52:53.830+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T02:52:53.831+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/extract_postgres.py", line 26, in extract_postgres
    df.to_csv(f"/shared/{table_name}.csv", index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/shared/order_line.csv'
[2025-06-22T02:52:53.870+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=extract, run_id=manual__2025-06-22T02:52:47.920817+00:00, execution_date=20250622T025247, start_date=20250622T025253, end_date=20250622T025253
[2025-06-22T02:52:54.067+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task extract ([Errno 13] Permission denied: '/shared/order_line.csv'; 46)
[2025-06-22T02:52:54.075+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T02:52:54.110+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T02:52:54.415+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
