[2025-06-22T01:35:00.524+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T01:35:00.569+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract manual__2025-06-22T01:34:38.738664+00:00 [queued]>
[2025-06-22T01:35:00.580+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract manual__2025-06-22T01:34:38.738664+00:00 [queued]>
[2025-06-22T01:35:00.591+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-22T01:35:00.687+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-06-22 01:34:38.738664+00:00
[2025-06-22T01:35:00.719+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=27) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-22T01:35:00.714+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'extract', 'manual__2025-06-22T01:34:38.738664+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp9hj3d_9x']
[2025-06-22T01:35:00.720+0000] {standard_task_runner.py:63} INFO - Started process 36 to run task
[2025-06-22T01:35:00.720+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask extract
[2025-06-22T01:35:01.544+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.extract manual__2025-06-22T01:34:38.738664+00:00 [running]> on host 6f2d380f552b
[2025-06-22T01:35:02.265+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T01:34:38.738664+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T01:34:38.738664+00:00'
[2025-06-22T01:35:02.269+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T01:35:02.419+0000] {logging_mixin.py:188} INFO - Extrayendo tabla: order_line
[2025-06-22T01:35:02.424+0000] {logging_mixin.py:188} WARNING - /opt/airflow/dags/scripts/extract_postgres.py:25 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-22T01:35:02.463+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T01:35:02.464+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/extract_postgres.py", line 26, in extract_postgres
    df.to_csv(f"/opt/airflow/tmp/{table_name}.csv", index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/airflow/tmp'
[2025-06-22T01:35:02.488+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=extract, run_id=manual__2025-06-22T01:34:38.738664+00:00, execution_date=20250622T013438, start_date=20250622T013500, end_date=20250622T013502
[2025-06-22T01:35:02.525+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task extract (Cannot save file into a non-existent directory: '/opt/airflow/tmp'; 36)
[2025-06-22T01:35:02.548+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T01:35:02.568+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T01:35:02.592+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
