[2025-06-22T01:47:55.980+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T01:47:56.012+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load manual__2025-06-22T01:47:46.242888+00:00 [queued]>
[2025-06-22T01:47:56.024+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load manual__2025-06-22T01:47:46.242888+00:00 [queued]>
[2025-06-22T01:47:56.026+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-22T01:47:56.058+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2025-06-22 01:47:46.242888+00:00
[2025-06-22T01:47:56.070+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'load', 'manual__2025-06-22T01:47:46.242888+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpm1bl2se5']
[2025-06-22T01:47:56.073+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask load
[2025-06-22T01:47:56.074+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=46) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-22T01:47:56.075+0000] {standard_task_runner.py:63} INFO - Started process 55 to run task
[2025-06-22T01:47:56.156+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.load manual__2025-06-22T01:47:46.242888+00:00 [running]> on host f6705842a464
[2025-06-22T01:47:56.275+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T01:47:46.242888+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T01:47:46.242888+00:00'
[2025-06-22T01:47:56.276+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T01:47:56.289+0000] {TSocket.py:149} INFO - Could not connect to ('172.19.0.2', 10000)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/thrift/transport/TSocket.py", line 144, in open
    handle.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-06-22T01:47:56.290+0000] {TSocket.py:152} ERROR - Could not connect to any of [('172.19.0.2', 10000)]
[2025-06-22T01:47:56.291+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T01:47:56.291+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load_to_hive.py", line 17, in load_to_hive
    conn = hive.Connection(host='hive-server', port=10000, username='hive')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyhive/hive.py", line 269, in __init__
    self._transport.open()
  File "/home/airflow/.local/lib/python3.12/site-packages/thrift_sasl/__init__.py", line 74, in open
    self._trans.open()
  File "/home/airflow/.local/lib/python3.12/site-packages/thrift/transport/TSocket.py", line 153, in open
    raise TTransportException(type=TTransportException.NOT_OPEN, message=msg)
thrift.transport.TTransport.TTransportException: Could not connect to any of [('172.19.0.2', 10000)]
[2025-06-22T01:47:56.306+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=load, run_id=manual__2025-06-22T01:47:46.242888+00:00, execution_date=20250622T014746, start_date=20250622T014756, end_date=20250622T014756
[2025-06-22T01:47:56.338+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task load (Could not connect to any of [('172.19.0.2', 10000)]; 55)
[2025-06-22T01:47:56.369+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T01:47:56.388+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T01:47:56.390+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
