[2025-06-22T01:12:16.252+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T01:12:16.302+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract manual__2025-06-22T01:11:57.499944+00:00 [queued]>
[2025-06-22T01:12:16.317+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract manual__2025-06-22T01:11:57.499944+00:00 [queued]>
[2025-06-22T01:12:16.321+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-22T01:12:16.360+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-06-22 01:11:57.499944+00:00
[2025-06-22T01:12:16.383+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'extract', 'manual__2025-06-22T01:11:57.499944+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmptylq15v4']
[2025-06-22T01:12:16.389+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask extract
[2025-06-22T01:12:16.390+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=39) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-22T01:12:16.391+0000] {standard_task_runner.py:63} INFO - Started process 48 to run task
[2025-06-22T01:12:16.611+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.extract manual__2025-06-22T01:11:57.499944+00:00 [running]> on host 0f8bd856b90f
[2025-06-22T01:12:16.962+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T01:11:57.499944+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T01:11:57.499944+00:00'
[2025-06-22T01:12:16.966+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T01:12:20.566+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T01:12:20.568+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/extract_postgres.py", line 5, in extract_postgres
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known

[2025-06-22T01:12:20.595+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=extract, run_id=manual__2025-06-22T01:11:57.499944+00:00, execution_date=20250622T011157, start_date=20250622T011216, end_date=20250622T011220
[2025-06-22T01:12:20.679+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task extract (could not translate host name "postgres" to address: Name or service not known
; 48)
[2025-06-22T01:12:20.712+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T01:12:20.743+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T01:12:20.783+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
