[2025-06-22T01:12:05.781+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T01:12:05.844+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract scheduled__2025-06-21T00:00:00+00:00 [queued]>
[2025-06-22T01:12:05.861+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract scheduled__2025-06-21T00:00:00+00:00 [queued]>
[2025-06-22T01:12:05.862+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-22T01:12:05.906+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-06-21 00:00:00+00:00
[2025-06-22T01:12:05.936+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'extract', 'scheduled__2025-06-21T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp03pigrdz']
[2025-06-22T01:12:05.946+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=29) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-22T01:12:05.948+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask extract
[2025-06-22T01:12:05.949+0000] {standard_task_runner.py:63} INFO - Started process 38 to run task
[2025-06-22T01:12:06.208+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.extract scheduled__2025-06-21T00:00:00+00:00 [running]> on host 0f8bd856b90f
[2025-06-22T01:12:06.498+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-06-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-21T00:00:00+00:00'
[2025-06-22T01:12:06.502+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T01:12:10.383+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T01:12:10.385+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/extract_postgres.py", line 5, in extract_postgres
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known

[2025-06-22T01:12:10.413+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=extract, run_id=scheduled__2025-06-21T00:00:00+00:00, execution_date=20250621T000000, start_date=20250622T011205, end_date=20250622T011210
[2025-06-22T01:12:10.475+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task extract (could not translate host name "postgres" to address: Name or service not known
; 38)
[2025-06-22T01:12:10.506+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T01:12:10.532+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T01:12:10.562+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-22T01:30:15.866+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T01:30:15.896+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract scheduled__2025-06-21T00:00:00+00:00 [queued]>
[2025-06-22T01:30:15.912+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract scheduled__2025-06-21T00:00:00+00:00 [queued]>
[2025-06-22T01:30:15.912+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-22T01:30:15.961+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2025-06-21 00:00:00+00:00
[2025-06-22T01:30:15.977+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'extract', 'scheduled__2025-06-21T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmplpjrl2j5']
[2025-06-22T01:30:15.981+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask extract
[2025-06-22T01:30:15.986+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=29) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-22T01:30:15.987+0000] {standard_task_runner.py:63} INFO - Started process 38 to run task
[2025-06-22T01:30:16.104+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.extract scheduled__2025-06-21T00:00:00+00:00 [running]> on host dfc0b5b0af93
[2025-06-22T01:30:16.288+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-06-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-21T00:00:00+00:00'
[2025-06-22T01:30:16.290+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T01:30:19.879+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T01:30:19.880+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/extract_postgres.py", line 5, in extract_postgres
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known

[2025-06-22T01:30:19.894+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=extract, run_id=scheduled__2025-06-21T00:00:00+00:00, execution_date=20250621T000000, start_date=20250622T013015, end_date=20250622T013019
[2025-06-22T01:30:19.919+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task extract (could not translate host name "db" to address: Name or service not known
; 38)
[2025-06-22T01:30:19.940+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T01:30:19.962+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T01:30:19.979+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
